cutoutPathPlants = ['Y:\\PWP-LIBRARY\\CUTOUTS\\PLANTS\\ALL PLANTS Collection', 'Y:\\PWP-LIBRARY\\CUTOUTS\\PLANTS\\AUSSIE NZ Collection', 'Y:\\PWP-LIBRARY\\CUTOUTS\\PLANTS\\TEMPERATE Collection', 'Y:\\PWP-LIBRARY\\CUTOUTS\\PLANTS\\TEMPERATE Collection']

cutoutPathPeople = ['Y:\\PWP-LIBRARY\\CUTOUTS\\PEOPLE\\PHOTO PEOPLE']